---
# Ronald Mulyono Abadi
# DBS Foundation Coding Camp 2023, Learning Path DevOps Engineer
# Kelas Expert, Belajar Membangun Arsitektur Microservices
# Submission Proyek Akhir: Proyek Implementasi Asynchronous Communication
# pada Aplikasi E-Commerce App
# File: rabbitmq-service.yml

apiVersion: v1

# Membuat Service
kind: Service

metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    environment: proyek-akhir
      
spec:
  # Saya pakai NodePort bukan ClusterIP ya supaya lebih mudah
  type: NodePort
  # Melakukan port mapping, disamakan dengan yang di StatefulSet
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30001
    name: amqp    
  - port: 15672
    targetPort: 15672
    nodePort: 30002
    name: http      
  - port: 4369
    targetPort: 4369
    nodePort: 30003
    name: discovery
  selector:
    app: rabbitmq
    environment: proyek-akhir
